### ISSUE TITLE
Better compatibility with Transmission's RPC protocol?

### ISSUE THREAD

**Issue by diizzyy** [BiglySoftware/BiglyBT-plugin-xmwebui#3]
According to https://wiki.vuze.com/w/Vuze_Web_Remote this plugin aims to be at least somewhat compatible with Transmission's RPC procotol however trying two different frontends shows that it's barely at best. It would be a great enhancement to BiglyBT if played nice with software that supports Transmission.

There are more around but I tested two and neither worked.

https://github.com/transmission-remote-gui/transgui (fails to add torrents/magnet links)
https://code.google.com/archive/p/transmission-remote-dotnet/downloads (outdated but can add torrents, magnet links doesn't work)

**Comment by moham96** [comment]
I second this, there are alot of different interfaces than transmission/vuze default ugly one and i tested some myself 

https://github.com/endor/kettu worked
https://github.com/killemov/Shift didn't work
https://github.com/ronggang/transmission-web-control didn't work
https://secretmapper.github.io/combustion/ worked

other not released frontends that look nice:
https://forum.transmissionbt.com/viewtopic.php?f=8&t=17862 
https://forum.transmissionbt.com/viewtopic.php?f=8&t=16762

**Comment by moham96** [comment]
@diizzyy  Was the issue resolved? I still have problems here.

**Comment by diizzyy** [comment]
No, it wasn't

**Comment by moham96** [comment]
@diizzyy So why close it?

**Comment by diizzyy** [comment]
Because it doesn't seem to go anywhere

**Comment by moham96** [comment]
@diizzyy I think you should reopen it, it should be closed by the authors when it is resolved.
But  it's up to you if you don't want to follow up on the issue

**Comment by diizzyy** [comment]
@moham96 
I'm no longer using BiglyBT so I'd suggest you reopen it if you're still interested.

**Comment by TuxPaper** [comment]
Please file a new Issue if you are seeing problems.  I went through quite a few transmission frontends a month or two ago and got them working (with xmwebui plugin changes).  I'll see if I can dig up which ones I tested.

**Comment by TuxPaper** [comment]
Ones that I tested at the end of June:
[ronggang/transmission-web-control](https://github.com/ronggang/transmission-web-control)
[Secretmapper/combustion](https://github.com/Secretmapper/combustion)
[endor/kettu](https://github.com/endor/kettu)

There's always a possibility that we broke compatibility again, or I didn't test thoroughly enough

**Comment by moham96** [comment]
@TuxPaper well [combustion](https://github.com/Secretmapper/combustion) and [kettu](https://github.com/endor/kettu) was working before any changes, the only problem now is in [transmission-web-control](https://github.com/ronggang/transmission-web-control)
I will open a new issue.
