### ISSUE TITLE
xmwebui not accepting get request parameters

### ISSUE THREAD

**Issue by moham96** [BiglySoftware/BiglyBT-plugin-xmwebui#4]
Hi,
This is a follow up on [3](https://github.com/BiglySoftware/BiglyBT-plugin-xmwebui/issues/3). I'm trying to get some skins to work for biglybt, I tried [transmission-web-control](https://github.com/ronggang/transmission-web-control) but it fails to retrieve some of the skin files 

> XML Parsing Error: no root element found
Location: http://localhost:9091/tr-web-control/lang/_languages.js?_=1517553460210
Line Number 1, Column 1:
_languages.js:1:1
XML Parsing Error: no root element found
Location: http://localhost:9091/tr-web-control/lang/default.js?_=1517553460209
Line Number 1, Column 1:

I digged more and found out the problem is that the server that comes with xmwebui doesn't allow get request parameters
so this fails:

> http://localhost:9091/tr-web-control/lang/_languages.js?_=1517553460210

while this works

> http://localhost:9091/tr-web-control/lang/_languages.js

I tried to modify the requests using a proxy and got the skin to load but not function so this might be a step in the right direction to get it working 
Also, another problem is that the web server is not redirecting requests with double slashes
so this fails
> http://localhost:9091//rpc

I suspect that these can be easily fixed and implemented, unfortunately, i don't program in java so I hope someone can fix them

**Comment by TuxPaper** [comment]
This change is in the BiglyBT core, so will be available in the next beta snapshot.  Unfortunately, the fix wasn't in the plugin itself, so we can't rollout a fix to existing BiglyBT users (until we release a new version of BiglyBT, of course)

**Comment by TuxPaper** [comment]
Thanks for the report.  It was clear and easy to follow
